name: docs

on:
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build docs
        uses: TinyTapeout/tt-gds-action/docs@3412659307918422f3f0727917cf9b499aaca588
        with:
          tools-ref: d66cf179e7bc4d296362ab7e2e3b344dc3c4f665
